// This file is auto-generated by @hey-api/openapi-ts

export const groupSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        }
    },
    required: ['id', 'name']
} as const;

export const eventSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        content: {
            anyOf: [
                {
                    type: 'object'
                }
            ]
        }
    },
    required: ['id', 'content']
} as const;