// This file is auto-generated by @hey-api/openapi-ts

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import type { Observable } from 'rxjs';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetGroupsResponse, PostGroupsData, PostGroupsResponse, GetGroupsByEventIdEventsData, GetGroupsByEventIdEventsResponse, PostGroupsByEventIdEventsData, PostGroupsByEventIdEventsResponse } from './types.gen';

/**
 * List groups
 * @returns group List of groups
 * @throws ApiError
 */
export const getGroups = function (): Observable<GetGroupsResponse> { return __request(OpenAPI, this.http, {
    method: 'GET',
    url: '/groups'
}); };

/**
 * Create group
 * @param data The data for the request.
 * @param data.requestBody
 * @returns group Group created
 * @throws ApiError
 */
export const postGroups = function (data: PostGroupsData): Observable<PostGroupsResponse> { return __request(OpenAPI, this.http, {
    method: 'POST',
    url: '/groups',
    body: data.requestBody,
    mediaType: 'application/json'
}); };

/**
 * Fetch changeset
 * @param data The data for the request.
 * @param data.eventId
 * @param data.since
 * @returns event Success
 * @throws ApiError
 */
export const getGroupsByEventIdEvents = function (data: GetGroupsByEventIdEventsData): Observable<GetGroupsByEventIdEventsResponse> { return __request(OpenAPI, this.http, {
    method: 'GET',
    url: '/groups/{eventId}/events',
    path: {
        eventId: data.eventId
    },
    query: {
        since: data.since
    }
}); };

/**
 * Create an event
 * @param data The data for the request.
 * @param data.eventId
 * @param data.requestBody
 * @returns event Created
 * @throws ApiError
 */
export const postGroupsByEventIdEvents = function (data: PostGroupsByEventIdEventsData): Observable<PostGroupsByEventIdEventsResponse> { return __request(OpenAPI, this.http, {
    method: 'POST',
    url: '/groups/{eventId}/events',
    path: {
        eventId: data.eventId
    },
    body: data.requestBody,
    mediaType: 'application/json'
}); };