// This file is auto-generated by @hey-api/openapi-ts

export type group = {
    id: string;
    name: string;
};

export type event = {
    id: string;
    content: ({
    [key: string]: unknown;
});
};

export type GetGroupsResponse = (Array<group>);

export type PostGroupsData = {
    requestBody: {
        name?: string;
    };
};

export type PostGroupsResponse = (group);

export type GetGroupsByEventIdEventsData = {
    eventId: string;
    since?: number;
};

export type GetGroupsByEventIdEventsResponse = (Array<event>);

export type PostGroupsByEventIdEventsData = {
    eventId: string;
    requestBody: {
        name?: string;
    };
};

export type PostGroupsByEventIdEventsResponse = (event);