openapi: 3.0.1

info:
  title: Debty API
  version: 1.0.0

paths:
  /groups:
    get:
      summary: List groups
      responses:
        '200':
          description: List of groups
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/group'
    post:
      summary: Create group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Group created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/group'
  /groups/{eventId}/events:
    get:
      summary: Fetch changeset
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: string
        - name: since
          in: query
          required: false
          schema:
            type: number
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/event'
    post:
      summary: Create an event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/event'

components:
  schemas:
    group:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name
    event:
      type: object
      properties:
        id:
          type: string
        content:
          anyOf:
            - type: object
      required:
        - id
        - content