openapi: 3.0.1

info:
  title: Debty API
  version: 1.0.0

paths:
  /groups:
    get:
      summary: List groups
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/group'
    post:
      summary: Create a group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/group'

components:
  schemas:
    group:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name